sudo: required
language: C

services:
- docker

before_install:
- docker info
- docker build -t andreaaletto/axc-adders-vhdl .
script:
- docker run andreaaletto/axc-adders-vhdl /bin/bash -c "mkdir /opt/build && cd /opt/build && cmake .. && make && make test"