#!/bin/bash

mkdir -p $HOME/vhdl_adders/vivado/src_links

ln -s $HOME/vhdl_adders/Src/Common/*.vhd $HOME/vhdl_adders/vivado/src_links
ln -s $HOME/vhdl_adders/Src/Cells/*.vhd $HOME/vhdl_adders/vivado/src_links
ln -s $HOME/vhdl_adders/Src/Adders/*.vhd $HOME/vhdl_adders/vivado/src_links
ln -s $HOME/vhdl_adders/Src/DCT/DCT1D/*.vhd $HOME/vhdl_adders/vivado/src_links
ln -s $HOME/vhdl_adders/Src/DCT/DCT2D/*.vhd $HOME/vhdl_adders/vivado/src_links
ln -s $HOME/vhdl_adders/Src/Wrappers/*.vhd $HOME/vhdl_adders/vivado/src_links