#!/bin/bash

# mkdir -p $HOME/vhdl_adders/vivado/src_links

ln -s $HOME/vhdl_adders/Src/Common/*.vhd $HOME/vhdl_adders/vivado/BC12/vhdl
ln -s $HOME/vhdl_adders/Src/Cells/*.vhd $HOME/vhdl_adders/vivado/BC12/vhdl
ln -s $HOME/vhdl_adders/Src/Adders/*.vhd $HOME/vhdl_adders/vivado/BC12/vhdl
ln -s $HOME/vhdl_adders/Src/DCT/DCT1D/BC121D.vhd $HOME/vhdl_adders/vivado/BC12/vhdl
ln -s $HOME/vhdl_adders/Src/DCT/DCT2D/BC12.vhd $HOME/vhdl_adders/vivado/BC12/vhdl
ln -s $HOME/vhdl_adders/Src/Wrappers/BC12Wrapper.vhd $HOME/vhdl_adders/vivado/BC12/vhdl

