#!/bin/bash


REPO_PATH=$HOME/vhdl_adders

mkdir -p $REPO_PATH/vivado/BC12/vhdl
mkdir -p $REPO_PATH/vivado/CB11/vhdl
mkdir -p $REPO_PATH/vivado/PEA12/vhdl
mkdir -p $REPO_PATH/vivado/PEA14/vhdl
mkdir -p $REPO_PATH/vivado/BAS08/vhdl
mkdir -p $REPO_PATH/vivado/BAS09/vhdl
mkdir -p $REPO_PATH/vivado/BAS11/vhdl

# Links for BC12

ln -fs $REPO_PATH/Src/Common/*.vhd $REPO_PATH/vivado/BC12/vhdl
ln -fs $REPO_PATH/Src/Cells/*.vhd $REPO_PATH/vivado/BC12/vhdl
ln -fs $REPO_PATH/Src/Adders/*.vhd $REPO_PATH/vivado/BC12/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT1D/BC121D.vhd $REPO_PATH/vivado/BC12/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT2D/BC12.vhd $REPO_PATH/vivado/BC12/vhdl
ln -fs $REPO_PATH/Src/Wrappers/BC12Wrapper.vhd $REPO_PATH/vivado/BC12/vhdl

# Links for CB11

ln -fs $REPO_PATH/Src/Common/*.vhd $REPO_PATH/vivado/CB11/vhdl
ln -fs $REPO_PATH/Src/Cells/*.vhd $REPO_PATH/vivado/CB11/vhdl
ln -fs $REPO_PATH/Src/Adders/*.vhd $REPO_PATH/vivado/CB11/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT1D/CB111D.vhd $REPO_PATH/vivado/CB11/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT2D/CB11.vhd $REPO_PATH/vivado/CB11/vhdl
ln -fs $REPO_PATH/Src/Wrappers/CB11Wrapper.vhd $REPO_PATH/vivado/CB11/vhdl

# Links for BAS11

ln -fs $REPO_PATH/Src/Common/*.vhd $REPO_PATH/vivado/BAS11/vhdl
ln -fs $REPO_PATH/Src/Cells/*.vhd $REPO_PATH/vivado/BAS11/vhdl
ln -fs $REPO_PATH/Src/Adders/*.vhd $REPO_PATH/vivado/BAS11/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT1D/BAS111D.vhd $REPO_PATH/vivado/BAS11/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT2D/BAS11.vhd $REPO_PATH/vivado/BAS11/vhdl
ln -fs $REPO_PATH/Src/Wrappers/BAS11Wrapper.vhd $REPO_PATH/vivado/BAS11/vhdl

# Links for BAS08

ln -fs $REPO_PATH/Src/Common/*.vhd $REPO_PATH/vivado/BAS08/vhdl
ln -fs $REPO_PATH/Src/Cells/*.vhd $REPO_PATH/vivado/BAS08/vhdl
ln -fs $REPO_PATH/Src/Adders/*.vhd $REPO_PATH/vivado/BAS08/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT1D/BAS081D.vhd $REPO_PATH/vivado/BAS08/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT2D/BAS08.vhd $REPO_PATH/vivado/BAS08/vhdl
ln -fs $REPO_PATH/Src/Wrappers/BAS08Wrapper.vhd $REPO_PATH/vivado/BAS08/vhdl

# Links for BAS09

ln -fs $REPO_PATH/Src/Common/*.vhd $REPO_PATH/vivado/BAS09/vhdl
ln -fs $REPO_PATH/Src/Cells/*.vhd $REPO_PATH/vivado/BAS09/vhdl
ln -fs $REPO_PATH/Src/Adders/*.vhd $REPO_PATH/vivado/BAS09/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT1D/BAS091D.vhd $REPO_PATH/vivado/BAS09/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT2D/BAS09.vhd $REPO_PATH/vivado/BAS09/vhdl
ln -fs $REPO_PATH/Src/Wrappers/BAS09Wrapper.vhd $REPO_PATH/vivado/BAS09/vhdl

# Links for PEA12

ln -fs $REPO_PATH/Src/Common/*.vhd $REPO_PATH/vivado/PEA12/vhdl
ln -fs $REPO_PATH/Src/Cells/*.vhd $REPO_PATH/vivado/PEA12/vhdl
ln -fs $REPO_PATH/Src/Adders/*.vhd $REPO_PATH/vivado/PEA12/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT1D/PEA121D.vhd $REPO_PATH/vivado/PEA12/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT2D/PEA12.vhd $REPO_PATH/vivado/PEA12/vhdl
ln -fs $REPO_PATH/Src/Wrappers/PEA12Wrapper.vhd $REPO_PATH/vivado/PEA12/vhdl

# Links for PEA14

ln -fs $REPO_PATH/Src/Common/*.vhd $REPO_PATH/vivado/PEA14/vhdl
ln -fs $REPO_PATH/Src/Cells/*.vhd $REPO_PATH/vivado/PEA14/vhdl
ln -fs $REPO_PATH/Src/Adders/*.vhd $REPO_PATH/vivado/PEA14/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT1D/PEA141D.vhd $REPO_PATH/vivado/PEA14/vhdl
ln -fs $REPO_PATH/Src/DCT/DCT2D/PEA14.vhd $REPO_PATH/vivado/PEA14/vhdl
ln -fs $REPO_PATH/Src/Wrappers/PEA14Wrapper.vhd $REPO_PATH/vivado/PEA14/vhdl